[workspace]
members = [
    "advent",
    "bloom",
    "c-exp",
    "collections-profiling",
    "fuzzing",
    "wasmvm",
    "stdlib",
    "mai-lang",
    "blackjack-rs",
    "roguelike",
    "bevygame",
    "searcher"
]
resolver = "2" # Important! wgpu/Bevy needs this!
