[package]
name = "advent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
serde = { version ="1.0.145", features = ["derive"] }
thiserror = "1.0.37"
eyre = "0.6.8"
